name:                souffle-haskell
synopsis:            Souffle Datalog bindings for Haskell
description:         Souffle Datalog bindings for Haskell.
version:             0.2.3
homepage:            https://github.com/luc-tielen/souffle-haskell#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2020 Luc Tielen
category:            Logic Programming, Foreign Binding, Bindings
github:              luc-tielen/souffle-haskell
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/souffle/LICENSE
  - cbits/**/*.h

dependencies:
  - base >= 4.12 && < 5
  - mtl >= 2.0 && < 3
  - template-haskell >= 2 && < 3
  - type-errors-pretty >= 0.0.1.0 && < 1
  - text >= 1.0 && < 2
  - vector <= 1.0
  - deepseq >= 1.4.4 && < 2
  - directory >= 1.3.3 && < 2
  - filepath  >= 1.4.2 && < 2
  - temporary >= 1.3 && < 2
  - process >= 1.6 && < 2

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17

include-dirs:
  - cbits
  - cbits/souffle

install-includes:
  - souffle/ReadStreamCSV.h
  - souffle/CompiledSouffle.h
  - souffle/SouffleInterface.h
  - souffle/UnionFind.h
  - souffle/EquivalenceRelation.h
  - souffle/gzfstream.h
  - souffle/swig/SwigInterface.h
  - souffle/WriteStreamSQLite.h
  - souffle/SignalHandler.h
  - souffle/Util.h
  - souffle/RamTypes.h
  - souffle/Logger.h
  - souffle/Table.h
  - souffle/CompiledRelation.h
  - souffle/ExplainTree.h
  - souffle/LambdaBTree.h
  - souffle/ReadStreamSQLite.h
  - souffle/IterUtils.h
  - souffle/ReadStream.h
  - souffle/BTree.h
  - souffle/IOSystem.h
  - souffle/IODirectives.h
  - souffle/SymbolTable.h
  - souffle/EventProcessor.h
  - souffle/PiggyList.h
  - souffle/json11.h
  - souffle/CompiledIndexUtils.h
  - souffle/ParallelUtils.h
  - souffle/CompiledTuple.h
  - souffle/ExplainProvenanceImpl.h
  - souffle/WriteStream.h
  - souffle/CompiledRecord.h
  - souffle/ProfileDatabase.h
  - souffle/ProfileEvent.h
  - souffle/ExplainProvenance.h
  - souffle/profile/htmlJsChartistPlugin.h
  - souffle/profile/htmlCssChartist.h
  - souffle/profile/Tui.h
  - souffle/profile/Relation.h
  - souffle/profile/Cli.h
  - souffle/profile/Iteration.h
  - souffle/profile/Table.h
  - souffle/profile/htmlJsChartistMin.h
  - souffle/profile/ProgramRun.h
  - souffle/profile/HtmlGenerator.h
  - souffle/profile/UserInputReader.h
  - souffle/profile/DataComparator.h
  - souffle/profile/htmlJsMain.h
  - souffle/profile/json11.h
  - souffle/profile/Rule.h
  - souffle/profile/htmlMain.h
  - souffle/profile/ProfileDatabase.h
  - souffle/profile/Reader.h
  - souffle/profile/htmlJsTableSort.h
  - souffle/profile/Row.h
  - souffle/profile/StringUtils.h
  - souffle/profile/CellInterface.h
  - souffle/profile/Cell.h
  - souffle/profile/OutputProcessor.h
  - souffle/profile/htmlJsUtil.h
  - souffle/profile/htmlCssStyle.h
  - souffle/WriteStreamCSV.h
  - souffle/CompiledOptions.h
  - souffle/Brie.h
  - souffle/BinaryConstraintOps.h
  - souffle/Explain.h

library:
  source-dirs:        lib
  cxx-sources:        cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
  generated-other-modules:
    - Paths_souffle_haskell

tests:
  souffle-haskell-test:
    main:             test.hs
    source-dirs:      tests
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - souffle-haskell
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__
